apiVersion: v1
kind: Namespace
metadata:
  name: ai-platform
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-core
  namespace: ai-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: platform-core
  template:
    metadata:
      labels:
        app: platform-core
    spec:
      containers:
      - name: api-gateway
        image: ai-platform/api-gateway:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch-service:9200
---
apiVersion: v1
kind: Service
metadata:
  name: platform-core-service
  namespace: ai-platform
spec:
  selector:
    app: platform-core
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
